name: Runner Unittests

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python: [3.10]

    steps:
    - name: Check repository
    - uses: actions/checkout@v4
    - name: Set up python
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10' 
    - name: Run Unittests
    - run: python Unittester.py
